"""Prompts module - LLM prompt templates."""
from prompts.intent_classification import (
    INTENT_CLASSIFICATION_TEMPLATE,
    INTENT_CLASSIFICATION_WITH_HISTORY_TEMPLATE
)
from prompts.sql_generation import (
    SQL_GENERATION_TEMPLATE,
    SQL_GENERATION_WITH_MEMORY_TEMPLATE
)
from prompts.answer_synthesis import (
    ANSWER_SYNTHESIS_TEMPLATE,
    ANSWER_WITH_ERROR_TEMPLATE
)

__all__ = [
    "INTENT_CLASSIFICATION_TEMPLATE",
    "INTENT_CLASSIFICATION_WITH_HISTORY_TEMPLATE",
    "SQL_GENERATION_TEMPLATE",
    "SQL_GENERATION_WITH_MEMORY_TEMPLATE",
    "ANSWER_SYNTHESIS_TEMPLATE",
    "ANSWER_WITH_ERROR_TEMPLATE",
]
